### ISSUE TITLE
[help] do not install yoastseo

### ISSUE THREAD

**Issue by vsmartcode** [gokulmhegde/Laravel-YoastSeo#11]
I installed the defective yoastseo package, please help me!
![image](https://user-images.githubusercontent.com/4949809/108590861-441e6d00-7398-11eb-95f4-46c4248b00d6.png)

**Comment by gokulmhegde** [comment]
Try to uninstall package with

**npm uninstall <package-name>**

**Comment by gokulmhegde** [comment]
> I installed the defective yoastseo package, please help me!
> ![image](https://user-images.githubusercontent.com/4949809/108590861-441e6d00-7398-11eb-95f4-46c4248b00d6.png)

I hope your issue might have resolved. 

I am closing this issue
